ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_provider VARCHAR(20);

CREATE TABLE IF NOT EXISTS revenuecat_webhook_events (
    id VARCHAR(255) PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
