ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100);

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS progress_message TEXT;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS caption_template VARCHAR(50) DEFAULT 'default';

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS include_broll BOOLEAN DEFAULT FALSE;

ALTER TABLE sources
ADD COLUMN IF NOT EXISTS url VARCHAR(1000);

UPDATE tasks SET progress = 0 WHERE progress IS NULL;
